### ISSUE TITLE
clEnqueueReadBuffer failed: out of resources

### ISSUE THREAD

**Issue by innsternet** [XMPPwocky/nodebeefcl#1]
> C:\Python27>python beef.py 18273 0.12345678 0.42424242 0.86737282
> Starting search...
> Traceback (most recent call last):
>   File "beef.py", line 57, in <module>
>     cl.enqueue_copy(queue, result_count_np, result_count_cl)
>   File "C:\Python27\lib\site-packages\pyopencl__init__.py", line 1086, in enqueue_copy
>     return _cl._enqueue_read_buffer(queue, src, dest, **kwargs)
> pyopencl.RuntimeError: clEnqueueReadBuffer failed: out of resources
> 
> C:\Python27>

I getting the following run time error when trying the example? I had a little look around and found [this](https://www.mail-archive.com/pyopencl@tiker.net/msg01767.html) which mentions it could be something to do with trying to write to out of bounds memory space?

**Comment by speedone** [comment]
I think the script must for nvidia graphics cards to be adjusted.

**Comment by XMPPwocky** [comment]
It appears that nVidia's OCL implementation has a cap of 5 seconds per job, so the search would need to be split up across multiple jobs... this should be possible, but I can't test it without an nVidia card. Looking into it.

**Comment by XMPPwocky** [comment]
With the recent optimizations, has this been fixed?
